### ISSUE TITLE
Remove Flow

### ISSUE THREAD

**Issue by stackptr** [freckle/react-hooks#174]
Flow bindings are generated because projects downstream were not yet converted to TypeScript. Recently, the last project was migrated, so this generation should be removed.

**Comment by joris974** [comment]
Probably this could be done as well for all our JS libs: 
- https://github.com/freckle/exhaustive-js
- https://github.com/freckle/parser-js
- https://github.com/freckle/maybe-js
- https://github.com/freckle/non-empty-js
- https://github.com/freckle/query-params-js
- https://github.com/freckle/resource-status-js
